---
name: build

on:
  push:
    branches:
      - master
      - renovate/**
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "samples/**"
      - "grafana/**"
      - "systemd/**"
      - "renovate.json"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "samples/**"
      - "grafana/**"
      - "systemd/**"
      - "renovate.json"

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version-file: go.mod
      - name: Ensure go.mod is already tidied
        run: go mod tidy && git diff --no-patch --exit-code
      - name: Run linters
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          # renovate: depName=golangci/golangci-lint datasource=github-releases
          version: v1.54.2
          args: --timeout=3m0s
      - name: Install richgo
        # renovate: depName=kyoh86/richgo
        run: go install github.com/kyoh86/richgo@v0.3.12
      - name: Run tests
        run: richgo test -race -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic -timeout 20m -v ./...
      - name: Send coverage
        uses: codecov/codecov-action@v3.1.4
        with:
          files: coverage.txt
      - name: Build with Goreleaser
        uses: goreleaser/goreleaser-action@v4.4.0
        with:
          # renovate: depName=goreleaser/goreleaser datasource=github-releases
          version: v1.20.0
          args: release --snapshot --skip-publish --clean
        env:
          PRIVATE_ACCESS_TOKEN: placeholder
      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows_exporter_binaries
          path: dist\nvidia_gpu_exporter_windows_*\nvidia_gpu_exporter.exe
  msi:
    needs: build
    runs-on: windows-2022
    steps:
      - name: Download Windows Artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows_exporter_binaries
      - name: Display structure of downloaded files
        run: ls -R