---
name: build

on:
  push:
    branches:
      - master
      - renovate/**
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "samples/**"
      - "grafana/**"
      - "systemd/**"
      - "renovate.json"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "samples/**"
      - "grafana/**"
      - "systemd/**"
      - "renovate.json"

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version-file: go.mod
      - name: Ensure go.mod is already tidied
        run: go mod tidy && git diff --no-patch --exit-code
      - name: Run linters
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          # renovate: depName=golangci/golangci-lint datasource=github-releases
          version: v1.54.2
          args: --timeout=3m0s
      - name: Install richgo
        # renovate: depName=kyoh86/richgo
        run: go install github.com/kyoh86/richgo@v0.3.12
      - name: Run tests
        run: richgo test -race -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic -timeout 20m -v ./...
      - name: Send coverage
        uses: codecov/codecov-action@v3.1.4
        with:
          files: coverage.txt
      - name: Build with Goreleaser
        uses: goreleaser/goreleaser-action@v4.4.0
        with:
          # renovate: depName=goreleaser/goreleaser datasource=github-releases
          version: v1.20.0
          args: release --snapshot --skip-publish --clean
        env:
          PRIVATE_ACCESS_TOKEN: placeholder
      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows_exporter_binaries
          path: |
            dist/nvidia_gpu_exporter_windows_*/
  msi:
    needs: build
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version-file: go.mod

      - name: Download Windows Artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows_exporter_binaries

      - name: Display structure of downloaded files
        run: ls -R

      - name: Build Release Artifacts
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          $ErrorActionPreference = "Stop"
          $TagName = $env:GITHUB_REF -replace 'refs/tags/', ''
          # The MSI version is not semver compliant, so just take the numerical parts
          $MSIVersion = $TagName -replace '^v?([0-9\.]+).*$','$1'
          foreach($Arch in "amd64_v1", "386") {
            Write-Verbose "Building windows_exporter $MSIVersion msi for $Arch"
            .\installer\build.ps1 -PathToExecutable .\nvidia_gpu_exporter\nvidia_gpu_exporter_windows_$Arch/nvidia_gpu_exporter.exe -Version $MSIVersion -Arch "$Arch"
            Move-Item installer\Output\nvidia_gpu_exporter_$MSIVersion_$Arch.msi dist\
          }
      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows_exporter_binaries
          path: dist
